# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: set token in config.yml
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: sed -i 's/token_value/$TOKEN/g' config.yml
    - name: set prefix in config.yml
      env:
        PREFIX: ${{ secrets.PREFIX }}
      run: sed -i 's/prefix_value/$PREFIX/g' config.yml
    - name: set ownerId in config.yml
      env:
        OWNER_ID: ${{ secrets.OWNER_ID }}
      run: sed -i 's/owner_value/$OWNER_ID/g' config.yml
    - name: set version in config.yml
      env:
        VERSION: ${{ secrets.VERSION }}
      run: sed -i 's/version_value/$VERSION/g' config.yml
    - name: set fixerKey in config.yml
      env:
        FIXER_KEY: ${{ secrets.FIXER_KEY }}
      run: sed -i 's/fixer_value/$FIXER_KEY/g' config.yml
    - name: set url of spuppyDB in config.yml
      env:
        SPUPPYDB_URL: ${{ secrets.SPUPPYDB_URL }}
      run: sed -i 's/spuppy_url/$SPUPPYDB_URL/g' config.yml
    - name: set user of spuppyDB in config.yml
      env:
        SPUPPYDB_USER: ${{ secrets.SPUPPYDB_USER }}
      run: sed -i 's/spuppy_user/$SPUPPYDB_USER/g' config.yml
    - name: set password of spuppyDB in config.yml
      env:
        SPUPPYDB_PASSWORD: ${{ secrets.SPUPPYDB_PASSWORD }}
      run: sed -i 's/spuppy_password/$SPUPPYDB_PASSWORD/g' config.yml
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
